algoritmo "Aula 3 - funções aritmeticas"
// Função :
// Autor :
// Data : 24/08/2020
// Seção de Declarações 
var
   a: inteiro
   raiz, pii, expo: real
inicio
      a <- abs (-50)
      escreval ("o valor absoluto de -50 é ", a)
      
      raiz <- raizq (90)
      escreval ("a raiz quadrada de 90 é: ", raiz)
      
      raiz <- int(raizq(90))
      escreval ("o numero inteiro da raiz quadrada de 90 é: ", raiz)
      
      pii <-  pi
      escreval ("o valor de PI é: ", pii)
      
      expo <- exp (3,2)
      escreval ("3^2 (três ao quadrado é): ", expo)
// Seção de Comandos 
fimalgoritmo
